#!/bin/bash

die () {
        echo "ERROR: $1. Aborting!"
        exit 1
}

if [ $UID -ne 0 ]; then
   die "$0 must be run as root"
fi
useradd -m -s /bin/bash runnerpyzza
passwd runnerpyzza
id runnerpyzza > /dev/null
if [ $? -ne 0 ]; then
   echo "Could not create the user runnerpyzza!"
   exit $?
fi
echo "User runnerpyzza successefully created"
