#!/bin/bash
die () {
        echo "ERROR: $1. Aborting!"
        exit 1
}

if [ $UID -ne 0 ]; then
   die "$0 must be run as root"
fi
mkdir /opt/runnerpyzza
chmod 777 -R /opt/runnerpyzza
ls /opt/runnerpyzza > /dev/null
if [ $? -ne 0 ] ; then
  die "Could not create RunnerPyzza directory"
else
  echo "RunnerPyzza directory successefully created"
fi
